### ISSUE TITLE
Button appears disabled if invoked code involves an await

### ISSUE THREAD

**Issue by AlMcLeanYF** [CommunityToolkit/dotnet#273]
### Describe the bug

I have been experimenting with Maui and the CommunityToolkit in a sample app.
I have wired up a button to use [ICommand], which executes code in a service.
When running as a windows app I have found if the lower level code includes the line 'await Task.Delay(3000);' then the button appears to be disabled, when it actually isn't. I believe that this is a bug. This behaviour does not happen when running with an android emulator.

I observed this problem with versions 8.0.0.0-preview2 and 8.0.0.0-preview3.

### Regression

8.0.0.0-preview1

### Steps to reproduce

```text
Check out the code from my repo here https://github.com/AlMcLeanYF/MauiApp1
Run it under windows
Go to 'Second Page' from the nav on the left
Click the 'Add Character' button

The will now appear disabled, and remain that way, although it can still be clicked
```

### Expected behavior

Once clicked the button should not change appearance.

### Screenshots

The image below shows that the button now appears disabled.

![image](https://user-images.githubusercontent.com/72981567/170671169-09b0349b-f5fc-4896-9df2-89a1c91c01ca.png)

### IDE and version

VS 2022 Preview

### IDE version

Version 17.3.0 Preview 1.1

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0.0-preview2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is a known issue in Preview2 and has been fixed by #139. Please update to Preview3 🙂

**Comment by AlMcLeanYF** [comment]
Hi

I think that this problem still persists with preview3. I have just updated my sample app to use that version.

(I noticed it at first with preview3, but rolled it back to preview2 since that was where the problem seemed to be introduced)

Cheers

Al
