### ISSUE TITLE
Source Generators use init-only setters, hindering support for .NET Standard 2.0

### ISSUE THREAD

**Issue by JonAdamsFromNC** [CommunityToolkit/dotnet#508]
### Describe the bug

I am attempting to use the Source Generations with a .NET Standard 2.0 project (in fact, Framework 4.8 WPF) - however the Source Generator Attributes seem to utilize init-only setters, which is unavailable in C# 7.3, the supported version for Standard 2.0.
Is .NET Standard 2.0 is no longer supported, or just the Source Generators are not compatible? Of course I could exclude the CanExecute parameter and everything works fine, but I'd like to use the full features!

### Steps to reproduce

```text
1. WPF project, .NET Framework 4.8, C# Language Version 7.3
2. Attempt to use the following code:

[RelayCommand(CanExecute = nameof(CanAddAttribute))]
private void AddAttribute(string newName)
{ }

3. Compiler fails to build with:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8370	Feature 'init-only setters' is not available in C# 7.3. Please use language version 9.0 or greater.
```

### Expected behavior

I expected this to be compatible with .NET Standard 2.0, and therefore with C# language version 7.3.

### IDE and version

VS 2022

### IDE version

17.2.6

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0.0

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
Hey there! I think this might've already been fixed by #376, could you try with 8.1.0-preview1 and let us know? Thank you! 😄

**Comment by JonAdamsFromNC** [comment]
Still occurring with 8.1.0-preview1 from Nuget!
A couple more details:
1. It does not appear that the source generators are working at all - none of the generated properties show as available via Intellisense.
2. Manually setting project language version to 8.0 or 9.0 seems to enable source generators.
3. The csproj is an MSBuild style, not SDK style, because I created it as a Framework 4.8 project in Visual Studio.

**Comment by Sergio0694** [comment]
That error seems to be from VS trying to load an invalid assembly. Hey @sharwell, would you know why is VS 17.2.6 trying to load the Roslyn 4.3 target of the analyzers here? Shouldn't it pick up the 4.0 target instead, which should then work? 🤔

**Comment by JonAdamsFromNC** [comment]
It seems if I create a class library targeting Standard 2.0, and choose 8.1.0 out of the gate, it chooses the right analyzer and gives no errors (aside from language version, until I set 8.0 manually). There's something weird with the order of operations and which framework is chosen to create the VS project - and specifically with WPF projects. Class library seems to work.
However, on the initial issue: A class library targeting 2.0, using v8.1.0-preview1, still gives "Feature init-only setters not available in C# 8.0…"

**Comment by Sergio0694** [comment]
Just tried this, but I don't think it's an issue. You're correct that you can't set those attribute properties at all on C# 7.3 due to them using init-only setters, but I think that's fine, because all source generators only work with C# 8.0 and up anyway. That is, even if that property wasn't using an init-only setter, the analyzer in the MVVM Toolkit would then emit a warning anyway telling you that C# 8.0 or greater is needed to use the source generator, and the generator would be disabled anyway.

So essentially this is by design I would say 🙂

> "Is .NET Standard 2.0 is no longer supported, or just the Source Generators are not compatible?"

It's still perfectly supported, but we chose C# 8.0 as a baseline for the generators to simplify things. You can still use C# 8 and greater on .NET Standard 2.0 as well, you'll just have to manually set `<LangVersion>` in your .csproj file.

**Comment by sharwell** [comment]
@Sergio0694 The targets files that select the correct Roslyn version for analyzers within a NuGet package is only implemented for SDK projects. Some of the project templates may still produce projects using the old style project file, and these will not be able to select the correct Roslyn version.

**Comment by JonAdamsFromNC** [comment]
@sharwell I believe that explains the behavior I was seeing. Everything behaves correctly and as expected, requiring language version 8.0, when the project is an SDK project.

The init-only setter "issue" is still there when targeting language version 8.0, but hey, if I'm setting language version, might as well be 9.0 instead.

Thanks @Sergio0694  and @sharwell for the assistance.
